stages:
  - deploy

deploy:
  stage: deploy
  image: node:22-alpine
  tags:
    - gitlab-runner-x86
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .next/cache/
  script:
    - apk add --no-cache bash
    - npm ci
    - npx -y netlify-cli deploy --prod --message="$CI_COMMIT_TITLE"
  only:
    - master
