stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - gitlab-runner-x86
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .next/cache/
  script:
    - npm ci
    - npm run build
    - npx netlify deploy --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
  only:
    - master
