stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - gitlab-runner-x86
  script:
    - apk add --no-cache curl
    - 'curl -s -X POST https://api.netlify.com/build_hooks/6996070abfa9845d319625f7'
    - echo "Netlify build triggered successfully"
  only:
    - master
